config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tutors, only: [:show, :index]
  resources :profiles
  mount RailsAdmin::Engine => '/backstage', as: 'rails_admin'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
	def self.convert_to_dollars(pennies)
		value = pennies.to_i * 0.01
	end

	belongs_to :user
end

app/models/tutor.rb
class Tutor
	# scope of Profile where is_tutor? == true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  def create
    @profile = Profile.new(profile_params)

    if @profile.save
      redirect_to @profile, notice: 'Profile was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /profiles/1
  def update
    if @profile.update(profile_params)
      redirect_to @profile, notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /profiles/1
  def destroy
    @profile.destroy
    redirect_to profiles_url, notice: 'Profile was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end


    # Only allow a trusted parameter "white list" through.
    def profile_params
      params.require(:profile).permit(:full_name, :mobile_phone, :biography)
    end
end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController
  def index
  	@tutors = Profile.where(is_tutor: true)
  end

  def show
  	@tutor = Profile.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_become_a_tutor_banner.html.erb
<div class="container-fluid verticalpadlarge slate-bg">

  <div class="container become-a-tutor">
    <div class="col-md-6">
      <div class="twohundred white">
        <h2>Become a <span class="brand" style="font-size: 140%;">High Performance</span> Tutor</h2>
        <p class="lead">Apply now to see if you have what it takes to become a qualified tutor in your area.</p>
        <a href="/become_a_tutor" class="button">Apply Now</a>
      </div>
    </div>

  </div>
</div>

app/views/application/_features.html.erb
<div class="grid-container full features">
  <div class="grid-x grid-margin-x">
    <div class="cell small-4">
        <i class="fa fa-map-marker fa-4x" aria-hidden="true"></i>
        <h2>Amazing Local Tutors</h2>
        <p class="lead">We handpick only the best tutors in your area.</p>
    </div>
    <div class="cell small-4">
        <i class="fa fa-compass fa-4x" aria-hidden="true"></i>
        <h2>Anytime, Anyplace</h2>
        <p class="lead">Tutoring around your schedule. Our tutors come to you!</p>
	
    </div>
    <div class="cell small-4">
        <i class="fa fa-check fa-4x" aria-hidden="true"></i>
        <h2>Easy &amp; Guaranteed.</h2>
        <p class="lead">We handle payment and scheduling. Any Issues? We’ll make it right!</p>
	</div>
  </div>
</div>

app/views/application/_footer.html.erb
<footer class="responsive-blog-footer">
  <div class="row">
    <div class="medium-8 columns small-order-2 medium-order-1 about-container">
      <div class="row">
        <div class="hide-for-small-only medium-4 columns about-section">
          <img src="https://placehold.it/250x250">
        </div>
        <div class="medium-8 columns about-section">
          <h4> About Me</h4>
          <p>paragraph about how amazing and awesome i am paragraph about how amazing and awesome i am paragraph about how amazing and awesome i am</p>
          <a href="">Read More</a>
        </div>
      </div>
    </div>
    <div class="small-12 medium-4 columns small-order-1 medium-order-2 mailing-container">
      <h4 class="mailing-list">Join my mailing list</h4>
      <input type="text" placeholder="Email Address">
      <a class="button expanded subscribe-button" href="#">Subscribe Now</a>
    </div>
  </div>
  <div class="row tag-search">
    <div class="columns">
      <h4>Search by Tag</h4>
      <ul class="menu simple tag-section">
        <li><a href="">word</a></li>
        <li><a href="">word</a></li>
        <li><a href="">word</a></li>
        <li><a href="">word</a></li>
        <li><a href="">word</a></li>
        <li><a href="">word</a></li>
        <li><a href="">word</a></li>
      </ul>
    </div>
  </div>
  <div class="row columns flex-container align-justify">
     <p> all rights reserved</p>
    <div class="up-arrow">
      <a href="#top"><i class="fa fa-chevron-circle-up" aria-hidden="true"></i></a>
    </div>
  </div>
</footer>

app/views/application/_header.html.erb
<!-- small screen -->
<!-- <header class="nav-mobile nav-locale-us nav-lang-en nav-ssl nav-rec nav-blueheaven"> -->
    <header class="nav-mobile">
        <div class="grid-y medium-grid-frame">

    <%#= render partial: '/application/nav_mobile/nav_logobar'%>
    <%#= render partial: '/application/nav_mobile/offset' %>
            <div class="cell">
                <%= render partial: '/application/nav_mobile/off_canvas_hamburger_menu'%>            
            </div>
        </div>                
    </header>

<!-- medium screen -->
    <header class="nav-locale-us nav-lang-en nav-ssl nav-rec nav-opt-sprite show-for-medium">
    	<!--  small size is much different than medium and large -->
    	<div id="navbar" class="small-12">
    		<div id="nav-belt" class="medium-12">
				<%= render partial: 'nav_belt_nav_left' %>
    			<%= render partial: 'nav_belt_nav_fill'%>
				<%= render partial: 'nav_belt_nav_right' %>
				<%= render partial: 'nav_flyout_anchor'%>
    			<%= render partial: 'nav_flyout_iss_anchor'%>
    		</div>
    		<div id="nav-main" class="medium-12 nav-sprite">
				<%= render partial: 'nav_main_nav_left' %>
    			<%= render partial: 'nav_main_nav_fill'%>
				<%= render partial: 'nav_main_nav_right' %>
    			<div class="nav-left"></div>	
    			<div class="nav-fill"></div>
    			<div class="nav-right"></div>
    		</div>
			<%= render partial: 'nav_subnav_toaster'%>

    	</div>
      <%= render :partial => "navigation" %>
    
      
    </header>

app/views/application/_marketing_site_footer.html.erb
<footer class="marketing-site-footer">
  <div class="row medium-unstack">
    <div class="medium-4 columns">
      <h4 class="marketing-site-footer-name">Yeti Snowcone</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita dolorem accusantium architecto id quidem, itaque nesciunt quam ducimus atque.</p>
      <ul class="menu marketing-site-footer-menu-social simple">
        <li><a href="#"><i class="fa fa-youtube-square" aria-hidden="true"></i></a></li>
         <li><a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
         <li><a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i></a></li>
      </ul>
    </div>
    <div class="medium-4 columns">
       <h4 class="marketing-site-footer-title">Contact Info</h4>
      <div class="marketing-site-footer-block">
        <i class="fa fa-map-marker" aria-hidden="true"></i>
        <p>100 W Rincon<br>San Francisco, CA 94015</p>
      </div>
      <div class="marketing-site-footer-block">
        <i class="fa fa-phone" aria-hidden="true"></i>
        <p>1 (800) 555-5555</p>
      </div>
      <div class="marketing-site-footer-block">
        <i class="fa fa-envelope-o" aria-hidden="true"></i>
        <p>yetirules@fakeemail.com</p>
      </div>
    </div>
    <div class="medium-4 columns">
      <h4 class="marketing-site-footer-title">Instagram</h4>
      <div class="row small-up-3">
        <div class="column column-block">
          <img src="https://placehold.it/75" alt="" />
        </div>
        <div class="column column-block">
          <img src="https://placehold.it/75" alt="" />
        </div>
        <div class="column column-block">
          <img src="https://placehold.it/75" alt="" />
        </div>
        <div class="column column-block">
          <img src="https://placehold.it/75" alt="" />
        </div>
        <div class="column column-block">
          <img src="https://placehold.it/75" alt="" />
        </div>
        <div class="column column-block">
          <img src="https://placehold.it/75" alt="" />
        </div>
      </div>
    </div>
  </div>
  <div class="marketing-site-footer-bottom">
    <div class="row large-unstack align-middle">
      <div class="column">
        <p>&copy; 2017 No rights reserved</p>
      </div>
      <div class="column">
        <ul class="menu marketing-site-footer-bottom-links">
          <li><a href="#">Home</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Services</a></li>
          <li><a href="#">Works</a></li>
          <li><a href="#">News</a></li>
          <li><a href="#">Contact</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/application/_nav_belt_nav_fill.html.erb
<div class="nav-fill">

	          <script type="text/javascript">window.navmet.tmp=+new Date();</script>
	<div id="nav-search">
	  <div id="nav-bar-left"></div>
	  <form accept-charset="utf-8" action="/s/ref=nb_sb_noss" class="nav-searchbar" method="GET" name="site-search" role="search">
	    
	    <div class="nav-left">
	      <div class="nav-search-scope nav-sprite">
	<div class="nav-search-facade" data-value="search-alias=aps">
	  <span class="nav-search-label">All</span>
	  <i class="nav-icon"></i>
	</div>

	  <span id="searchDropdownDescription" style="display:none">Select the department you want to search in</span>

	<select aria-describedby="searchDropdownDescription" class="nav-search-dropdown searchSelect" data-nav-digest="ey6qg6evkGTF/R5BH4O7iyRQE7s" data-nav-selected="0" id="searchDropdownBox" name="url" style="display:block" tabindex="18" title="Search in">
	<option selected="selected" value="search-alias=aps">All Departments</option>
	<option value="search-alias=alexa-skills">Alexa Skills</option>
	<option value="search-alias=amazon-devices">Amazon Devices</option>
	<option value="search-alias=amazonfresh">Amazon Fresh</option>
	<option value="search-alias=warehouse-deals">Amazon Warehouse</option>
	<option value="search-alias=appliances">Appliances</option>
	<option value="search-alias=mobile-apps">Apps &amp; Games</option>
	<option value="search-alias=arts-crafts">Arts, Crafts &amp; Sewing</option>
	<option value="search-alias=automotive">Automotive Parts &amp; Accessories</option>
	<option value="search-alias=baby-products">Baby</option>
	<option value="search-alias=beauty">Beauty &amp; Personal Care</option>
	<option value="search-alias=stripbooks">Books</option>
	<option value="search-alias=popular">CDs &amp; Vinyl</option>
	<option value="search-alias=mobile">Cell Phones &amp; Accessories</option>
	<option value="search-alias=fashion">Clothing, Shoes &amp; Jewelry</option>
	<option value="search-alias=fashion-womens">&nbsp;&nbsp;&nbsp;Women</option>
	<option value="search-alias=fashion-mens">&nbsp;&nbsp;&nbsp;Men</option>
	<option value="search-alias=fashion-girls">&nbsp;&nbsp;&nbsp;Girls</option>
	<option value="search-alias=fashion-boys">&nbsp;&nbsp;&nbsp;Boys</option>
	<option value="search-alias=fashion-baby">&nbsp;&nbsp;&nbsp;Baby</option>
	<option value="search-alias=collectibles">Collectibles &amp; Fine Art</option>
	<option value="search-alias=computers">Computers</option>
	<option value="search-alias=courses">Courses</option>
	<option value="search-alias=financial">Credit and Payment Cards</option>
	<option value="search-alias=digital-music">Digital Music</option>
	<option value="search-alias=electronics">Electronics</option>
	<option value="search-alias=lawngarden">Garden &amp; Outdoor</option>
	<option value="search-alias=gift-cards">Gift Cards</option>
	<option value="search-alias=grocery">Grocery &amp; Gourmet Food</option>
	<option value="search-alias=handmade">Handmade</option>
	<option value="search-alias=hpc">Health, Household &amp; Baby Care</option>
	<option value="search-alias=local-services">Home &amp; Business Services</option>
	<option value="search-alias=garden">Home &amp; Kitchen</option>
	<option value="search-alias=industrial">Industrial &amp; Scientific</option>
	<option value="search-alias=digital-text">Kindle Store</option>
	<option value="search-alias=fashion-luggage">Luggage &amp; Travel Gear</option>
	<option value="search-alias=luxury-beauty">Luxury Beauty</option>
	<option value="search-alias=magazines">Magazine Subscriptions</option>
	<option value="search-alias=movies-tv">Movies &amp; TV</option>
	<option value="search-alias=mi">Musical Instruments</option>
	<option value="search-alias=office-products">Office Products</option>
	<option value="search-alias=pets">Pet Supplies</option>
	<option value="search-alias=prime-exclusive">Prime Exclusive Savings</option>
	<option value="search-alias=pantry">Prime Pantry</option>
	<option value="search-alias=instant-video">Prime Video</option>
	<option value="search-alias=software">Software</option>
	<option value="search-alias=sporting">Sports &amp; Outdoors</option>
	<option value="search-alias=tools">Tools &amp; Home Improvement</option>
	<option value="search-alias=toys-and-games">Toys &amp; Games</option>
	<option value="search-alias=vehicles">Vehicles</option>
	<option value="search-alias=videogames">Video Games</option>
	</select>

	</div>
	    </div>
	    <div class="nav-right">
	      <div class="nav-search-submit nav-sprite">
	        
	<span id="nav-search-submit-text" class="nav-search-submit-text nav-sprite">Go</span>

	        <input class="nav-input" value="Go" tabindex="20" type="submit">
	      </div>
	    </div>
	    <div class="nav-fill">
	      <div class="nav-search-field ">
	        <!-- DO NOT REMOVE: the text in the label are for screen reader, and it is not visible in the web page -->
	        <label id="nav-search-label" for="twotabsearchtextbox" class="aok-offscreen">
	          Search
	        </label>
	        <input id="twotabsearchtextbox" value="" name="field-keywords" autocomplete="off" placeholder="" class="nav-input" dir="auto" tabindex="19" type="text">
	      </div>
	      <div id="nav-iss-attach"></div>
	    </div>
	  </form>
	</div>
	<script type="text/javascript">window.navmet.push({key:'SearchBar',end:+new Date(),begin:window.navmet.tmp});</script>
</div>

app/views/application/_nav_belt_nav_right.html.erb
	<div class="nav-right">
		
		<!-- <script type="text/javascript">window.navmet.tmp=+new Date();</script> -->

		  <div id="nav-swmslot">
		    <div id="navSwmHoliday" style="background-image: url(https://images-na.ssl-images-amazon.com/images/G/01/digital/video/merch/2018/Other/P13366195_FridayMovieNightPMDMayWeek4/Amazon_GW_DesktopSWM_P13364951_FridayMovieNightWeek4GW_400x39_en_US._CB477614436_.jpg); width: 400px; height: 39px; overflow: hidden;position: relative;"><a href="/gp/redirect.html/ref=nav_swm_99¢ summer movie rentals?_encoding=UTF8&amp;location=https%3A%2F%2Fwww.amazon.com%2Fb%3Famp%253Bref%3Ddvm_us_tv_cs_sh_be_modapmd_i0%26node%3D17751916011&amp;source=standards&amp;token=6068EB21390732AD9AD3698DD4EF29AF31ADB6DB&amp;pf_rd_p=8f23a934-b010-42e9-b5e6-331c953bb32b&amp;pf_rd_s=nav-sitewide-msg&amp;pf_rd_t=4201&amp;pf_rd_i=navbar-4201&amp;pf_rd_m=ATVPDKIKX0DER&amp;pf_rd_r=8PRAEM3C8R9VMDFJE0MW&amp;pf_rd_r=8PRAEM3C8R9VMDFJE0MW&amp;pf_rd_p=8f23a934-b010-42e9-b5e6-331c953bb32b" class="nav-imageHref" alt="99¢ summer movie rentals" tabindex="21"></a></div>
		  </div>
		<script type="text/javascript">window.navmet.push({key:'SWM',end:+new Date(),begin:window.navmet.tmp});</script>

	</div>

app/views/application/_nav_flyout_iss_anchor.html.erb
<div id="nav-flyout-searchAjax" class="nav-issFlyout nav-flyout">
	<div class="nav-template nav-flyout-content"></div>
</div>

app/views/application/_nav_main_nav_fill.html.erb
<div class="nav-fill">
            
<div id="nav-shop">
  <a href="/gp/site-directory/ref=nav_shopall_btn" class="nav-a nav-a-2 nav-single-row-link" data-ux-jq-mouseenter="true" id="nav-link-shopall" tabindex="36"><span class="nav-line-1"></span><span class="nav-line-2">Departments<span class="nav-icon nav-arrow" style="visibility: visible;"></span></span></a>
</div>

            <div id="nav-xshop-container" class="">
              <div id="nav-xshop"><script type="text/javascript">window.navmet.tmp=+new Date();</script>

<a href="/gp/history/ref=nav_nav_timeline_view_history" class="nav-a" data-ux-jq-mouseenter="true" id="nav-recently-viewed" tabindex="48">Browsing History<span class="nav-icon nav-arrow" style="visibility: visible;"></span></a><a href="/gp/yourstore/home/ref=nav_cs_ys" class="nav-a" tabindex="49">Your Recommendations</a><a href="/gp/goldbox/ref=nav_cs_gb" class="nav-a" tabindex="50">Today's Deals</a><a href="/gift-cards/b/ref=nav_cs_gift_cards?ie=UTF8&amp;node=2238192011" class="nav-a" tabindex="51">Gift Cards</a><a href="/b/ref=nav_cs_registry?ie=UTF8&amp;node=16115931011" class="nav-a" tabindex="52">Registry</a><a href="/b/ref=nav_cs_sell?_encoding=UTF8&amp;ld=AZUSSOA-sell&amp;node=12766669011" class="nav-a" tabindex="53">Sell</a><a href="/treasuretruck/ref=nav_cs_treasuretruck" class="nav-a" tabindex="54">Treasure Truck</a><a href="/gp/help/customer/display.html/ref=nav_cs_help?ie=UTF8&amp;nodeId=508510" class="nav-a" tabindex="55">Help</a><a href="/gp/help/customer/accessibility" aria-label="Click to call our Disability Customer Support line, or reach us directly at 1-888-283-1678" class="nav-hidden-aria" tabindex="56">Disability Customer Support </a>
<script type="text/javascript">window.navmet.push({key:'CrossShop',end:+new Date(),begin:window.navmet.tmp});</script></div>
              
            </div>
        </div>

app/views/application/_nav_main_nav_left.html.erb
<div class="nav-left">
          
            
<div id="nav-global-location-slot"><span class="a-declarative" data-a-modal="{&quot;width&quot;:375,&quot;closeButton&quot;:&quot;false&quot;,&quot;popoverLabel&quot;:&quot;Choose your delivery location&quot;,&quot;name&quot;:&quot;glow-modal&quot;,&quot;url&quot;:&quot;/gp/glow/get-address-selections.html?selectedLocationType=&amp;selectedLocationValue=&amp;deviceType=desktop&amp;pageType=YourAccount&amp;storeContext=account&quot;,&quot;footer&quot;:&quot;<span class=\&quot;a-declarative\&quot; data-action=\&quot;a-popover-close\&quot; data-a-popover-close=\&quot;{}\&quot;><span class=\&quot;a-button a-button-primary\&quot;><span class=\&quot;a-button-inner\&quot;><button name=\&quot;glowDoneButton\&quot; class=\&quot;a-button-text\&quot; type=\&quot;button\&quot;>Done</button></span></span></span>&quot;,&quot;header&quot;:&quot;Choose your delivery location&quot;}" data-action="a-modal"><a class="nav-a nav-a-2 a-popover-trigger a-declarative" tabindex="35"><div class="nav-sprite" id="nav-packard-glow-loc-icon"></div><div id="glow-ingress-block"><span class="nav-line-1" id="glow-ingress-line1">Hello</span><span class="nav-line-2" id="glow-ingress-line2">Select your address</span></div></a></span><input data-addnewaddress="add-new" id="unifiedLocation1ClickAddress" name="dropdown-selection" value="add-new" type="hidden"><input data-addnewaddress="add-new" id="ubbShipTo" name="dropdown-selection-ubb" value="add-new" type="hidden"></div>




          
          
        </div>

app/views/application/_nav_main_nav_right.html.erb
<div class="nav-right">
          <script type="text/javascript">window.navmet.tmp=+new Date();</script>






<div id="nav-tools">
  
<a href="/gp/customer-preferences/select-language/ref=topnav_lang?ie=UTF8&amp;preferencesReturnUrl=%2Fref%3Dnav_logo" id="icp-nav-flyout" class="nav-a nav-a-2 icp-link-style-2">
  <span class="icp-nav-link-inner">
    <span class="nav-line-1">
      <span class="icp-nav-globe-img-2"></span>
      <span class="icp-nav-language">EN</span>
    </span>
    <span class="nav-line-2">&nbsp;
      <span class="nav-icon nav-arrow" style="visibility: visible;"></span>
    </span>
  </span>
  <span class="icp-nav-link-border"></span>
</a>
<a href="/gp/css/homepage.html/ref=nav_youraccount_btn" class="nav-a nav-a-2 nav-truncate nav-active" data-nav-ref="nav_ya_signin" data-nav-role="signin" data-ux-jq-mouseenter="true" id="nav-link-accountList" tabindex="61"><span class="nav-line-1">Hello, Carl</span><span class="nav-line-2">Account &amp; Lists<span class="nav-icon nav-arrow" style="visibility: visible;"></span></span><span class="nav-line-3">Hi Carl</span><span class="nav-line-4">Account &amp; Lists</span></a><a href="/gp/flex/sign-out.html/ref=nav_signout?ie=UTF8&amp;action=sign-out&amp;path=%2Fgp%2Fyourstore%2Fhome&amp;signIn=1&amp;useRedirectOnSuccess=1" class="nav-hidden-aria" tabindex="62">Not Carl? Sign Out </a><a href="/gp/css/order-history/ref=nav_nav_orders_first" class="nav-a nav-a-2 nav-single-row-link" id="nav-orders" tabindex="63"><span class="nav-line-1"></span><span class="nav-line-2">Orders</span></a><a href="/gp/prime/ref=nav_prime_member_btn" class="nav-a nav-a-2 nav-single-row-link" data-ux-jq-mouseenter="true" id="nav-link-prime" tabindex="64"><span class="nav-line-1"></span><span class="nav-line-2">Prime<span class="nav-icon nav-arrow" style="visibility: visible;"></span></span></a><a href="/gp/cart/view.html/ref=nav_cart" aria-label="10 items in cart" class="nav-a nav-a-2" id="nav-cart" tabindex="65"><span aria-hidden="true" class="nav-line-1"></span><span aria-hidden="true" class="nav-line-2">Cart<span class="nav-icon nav-arrow"></span></span><span class="nav-cart-icon nav-sprite"></span><span id="nav-cart-count" aria-hidden="true" class="nav-cart-count nav-cart-10">10</span></a>
</div>
<script type="text/javascript">window.navmet.push({key:'Tools',end:+new Date(),begin:window.navmet.tmp});</script>
        </div>

app/views/application/_nav_searchbar.html.erb
<!-- this is the second row in the small header -->
    <div class="grid-x grid-padding-x align-middle nav-searchbar-wrapper" id="searchbar">
    	<div class="cell auto">
    		<form class="nav-searchbar" action="/gp/aw/s/ref=is_s" method="get" role="search" id="nav-search-form" accept-charset="utf-8" style="display:inline-block;">
      			<div class="grid-x align-middle nav-right">
			      	<div class="nav-fill cell auto">
				        <div class="nav-search-field">
					          <input class="nav-input" placeholder="Search" aria-label="Type search keywords" data-aria-clear-label="Clear search keywords" name="k" autocomplete="off" autocorrect="off" autocapitalize="off" dir="auto" value="" id="nav-search-keywords" type="text">
					        <a class="nav-icon nav-sprite nav-search-clear" tabindex="0" href="javascript:;" aria-label="Clear search keywords"></a>
				    	</div>
			      	</div>
	      	        <div class="nav-search-submit cell shrink">
	          			<input class="button nav-input" value="Find Tutor" aria-label="Find Tutor" type="submit">
	        		</div>
      			</div>
    		</form>

    	</div>
<!-- 	    <div id="nav-microphone" class="nav-afap-search cell shrink">
	      <a href="https://dl.amazon.com/r/ref=mm_dl_from_voicesrch?campaignId=AFAPVoiceSearch&amp;failureMode=UserSelect&amp;url=https%3A%2F%2Fwww.amazon.com%2Fappfeature%2Fvoicesearch" class="nav-sprite nav-afap-search-icon"><%= fa_icon "microphone" %></a>
	    </div>
	    <div id="nav-camera" class="nav-afap-search cell shrink">
	      <a href="https://dl.amazon.com/r/ref=mm_dl_from_camsrch?campaignId=AFAPCameraSearch&amp;failureMode=UserSelect&amp;url=https%3A%2F%2Fwww.amazon.com%2Fproducts%3Fsearchtype%3Dflow" class="nav-sprite nav-afap-search-icon"><%= fa_icon "camera" %></a>
	    </div> -->
  	</div>

app/views/application/_profile_summary.html.erb
<div class="card cell medium-4 profile-summary-card">
  <div class="grid-x grid-margin-x">
    <div class="cell small-4 image-holder" style="padding: 8px">
      <%= image_tag profile_summary.user_photo_url, style: 'min-width: 64px;' %>
    </div>
    <div class="cell small-8 profile-summary-detail">
      <div class="profile-title">
        <%= link_to profile_summary.full_name, tutor_path(profile_summary) %>
      </div>
      <div class="secondary-line">
        <h3><%= number_to_currency(Profile.convert_to_dollars(profile_summary.hourly_rate_in_usd)) %><small>/hr</small></h3>
      </div>
      <div class="bona-fides">
         <span class="slate">
          <i class="fa fa-graduation-cap" aria-hidden="true"></i> 
          <%= profile_summary.accreditation %>
        </span>
      </div>
    </div>
  </div>  
</div>

app/views/application/nav_mobile/_nav_logobar.html.erb
<%= render partial: '/application/nav_mobile/off_canvas_hamburger_menu'%>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<div class="y-grid">
  <div class="cell">
    <%= render partial: 'tutor_profile_card'%>
  </div>
</div>



<p>
  <strong>Full name:</strong>
  <%= @profile.full_name %>
</p>

<p>
  <strong>Biography:</strong>
  <%= @profile.biography %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

app/views/tutors/show.html.erb
<% content_for(:title) { 'Find a Tutor' } %>
<h1>Tutors#show</h1>
<p>Find me in app/views/tutors/show.html.erb</p>
<div class="y-grid">
  <div class="cell">
    <%= render partial: 'tutor_profile_card'%>
  </div>
</div>



<p>
  <strong>Full name:</strong>
  <%= @tutor.full_name %>
</p>

<p>
  <strong>Biography:</strong>
  <%= @tutor.biography %>
</p>

<%= link_to 'Back', tutors_path %>